"""initial schema

Revision ID: fc1fde2d045a
Revises: 
Create Date: 2026-10-08 15:16:24.388411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import growth_engine.db


# revision identifiers, used by Alembic.
revision: str = 'fc1fde2d045a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bot_sessions',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('chat_id', sa.String(length=40), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'chat_id')
    )
    op.create_table('bot_updates',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('update_id', sa.String(length=32), nullable=False),
    sa.Column('at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'channel_id', 'update_id')
    )
    op.create_table('jobs',
    sa.Column('queue', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('locked_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['queue', 'status', 'run_at'], unique=False)
    op.create_index(op.f('ix_jobs_dedupe_key'), 'jobs', ['dedupe_key'], unique=False)
    op.create_table('otp_codes',
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('expires_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('pending_first_name', sa.String(length=80), nullable=True),
    sa.Column('pending_last_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('users',
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('agencies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('white_label', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audits',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('handle', sa.String(length=60), nullable=False),
    sa.Column('vertical', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('agency_id', sa.String(length=32), nullable=True),
    sa.Column('input_kind', sa.String(length=20), nullable=False),
    sa.Column('screenshot_keys', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('fixes', sa.JSON(), nullable=False),
    sa.Column('rewrites', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('wants_service', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('vertical', sa.String(length=40), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('agency_id', sa.String(length=32), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('brand_kits',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('fonts', sa.JSON(), nullable=False),
    sa.Column('tone', sa.JSON(), nullable=False),
    sa.Column('pillars', sa.JSON(), nullable=False),
    sa.Column('glossary', sa.JSON(), nullable=False),
    sa.Column('banned', sa.JSON(), nullable=False),
    sa.Column('templates', sa.JSON(), nullable=False),
    sa.Column('bio', sa.JSON(), nullable=False),
    sa.Column('logo_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_ok', sa.Boolean(), nullable=True),
    sa.Column('health_checked_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('health_error', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_analyses',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('posts_per_week', sa.Double(), nullable=True),
    sa.Column('engagement_rate', sa.Double(), nullable=True),
    sa.Column('best_hook', sa.String(length=120), nullable=True),
    sa.Column('last_collected_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'handle')
    )
    op.create_table('content_ideas',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pillar', sa.String(length=40), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('influencer', sa.String(length=80), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'code')
    )
    op.create_table('leads',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('keyword', sa.String(length=60), nullable=True),
    sa.Column('at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('bale_user_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('link_code', sa.String(length=12), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_code'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_table('offers',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('starts_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug')
    )
    op.create_table('plan_payments',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('amount_toman', sa.Integer(), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority')
    )
    op.create_table('reports',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_recipes',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('pillar', sa.String(length=40), nullable=True),
    sa.Column('caption_style', sa.String(length=500), nullable=False),
    sa.Column('cta', sa.String(length=200), nullable=False),
    sa.Column('video_spec', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('timing', sa.JSON(), nullable=False),
    sa.Column('low_risk', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tag')
    )
    op.create_table('usage_counters',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'month', 'metric')
    )
    op.create_table('audit_log',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('actor_member_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_member_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_posts',
    sa.Column('competitor_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('posted_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('offer_price', sa.String(length=120), nullable=True),
    sa.Column('hook_type', sa.String(length=40), nullable=True),
    sa.Column('ratio_to_avg', sa.Double(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'url')
    )
    op.create_table('keyword_replies',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('keyword', sa.String(length=60), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('offer_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'keyword')
    )
    op.create_table('media_assets',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_platform', sa.String(length=20), nullable=False),
    sa.Column('source_chat_id', sa.String(length=40), nullable=True),
    sa.Column('source_msg_id', sa.String(length=40), nullable=True),
    sa.Column('sender_member_id', sa.String(length=32), nullable=True),
    sa.Column('file_key', sa.String(length=200), nullable=True),
    sa.Column('duration_s', sa.Double(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('faces_detected', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_member_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('recipe_id', sa.String(length=32), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('tag_guessed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('raw_note', sa.Text(), nullable=False),
    sa.Column('output_duration_s', sa.Double(), nullable=True),
    sa.Column('qc', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('approved_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('auto_approve_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['tag_recipes.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_slots',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('pillar', sa.String(length=40), nullable=True),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('occasion', sa.String(length=120), nullable=True),
    sa.Column('offer_id', sa.String(length=32), nullable=True),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('idea_id', sa.String(length=32), nullable=True),
    sa.Column('needs_media', sa.Boolean(), nullable=False),
    sa.Column('request_sent_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_links',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('influencer', sa.String(length=80), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('clicks',
    sa.Column('link_id', sa.String(length=32), nullable=False),
    sa.Column('at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['tracked_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funnel_events',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=True),
    sa.Column('link_id', sa.String(length=32), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['tracked_links.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_variants',
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('video_key', sa.String(length=200), nullable=True),
    sa.Column('cover_key', sa.String(length=200), nullable=True),
    sa.Column('srt_key', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('tracked_link_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_link_id'], ['tracked_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'channel_id', 'kind')
    )
    op.create_table('registrations',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('offer_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('media_consent', sa.Boolean(), nullable=False),
    sa.Column('amount_toman', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=True),
    sa.Column('source_link_id', sa.String(length=32), nullable=True),
    sa.Column('source_coupon_id', sa.String(length=32), nullable=True),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['source_coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['source_link_id'], ['tracked_links.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority')
    )
    op.create_table('publications',
    sa.Column('variant_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', growth_engine.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['post_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('publication_id', sa.String(length=32), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'channel_type', 'external_id')
    )
    op.create_table('metric_snapshots',
    sa.Column('publication_id', sa.String(length=32), nullable=False),
    sa.Column('at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', growth_engine.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_snapshots')
    op.drop_table('feedback')
    op.drop_table('publications')
    op.drop_table('registrations')
    op.drop_table('post_variants')
    op.drop_table('funnel_events')
    op.drop_table('clicks')
    op.drop_table('tracked_links')
    op.drop_table('calendar_slots')
    op.drop_table('posts')
    op.drop_table('media_assets')
    op.drop_table('keyword_replies')
    op.drop_table('competitor_posts')
    op.drop_table('audit_log')
    op.drop_table('usage_counters')
    op.drop_table('tag_recipes')
    op.drop_table('reports')
    op.drop_table('plan_payments')
    op.drop_table('offers')
    op.drop_table('memberships')
    op.drop_table('leads')
    op.drop_table('coupons')
    op.drop_table('content_ideas')
    op.drop_table('competitors')
    op.drop_table('competitor_analyses')
    op.drop_table('channels')
    op.drop_table('brand_kits')
    op.drop_table('workspaces')
    op.drop_table('audits')
    op.drop_table('agencies')
    op.drop_table('users')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_jobs_dedupe_key'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('bot_updates')
    op.drop_table('bot_sessions')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
