// Every Persian string the panel shows. Components never hold Persian text;
// a missing key is a TypeScript error, not a blank in the UI.

export const fa = {
  product: "موتور رشد",
  common: {
    save: "ذخیره",
    saved: "ذخیره شد",
    cancel: "انصراف",
    delete: "حذف",
    add: "افزودن",
    edit: "ویرایش",
    loading: "در حال بارگذاری…",
    empty: "هنوز چیزی نیست.",
    toman: "تومان",
    yes: "بله",
    no: "خیر",
    print: "خروجی PDF (چاپ)",
    copy: "کپی",
    copied: "کپی شد",
    send: "ارسال",
    signOut: "خروج",
    back: "بازگشت",
    refresh: "به‌روزرسانی",
    listSep: "، ",
  },
  nav: {
    dashboard: "داشبورد",
    queue: "صف تأیید",
    calendar: "تقویم",
    brand: "کیت برند",
    tags: "تگ‌ها",
    feedback: "بازخورد",
    competitors: "رقبا",
    sales: "فروش و لینک‌ها",
    reports: "گزارش‌ها",
    channels: "کانال‌ها",
    team: "اعضا",
    settings: "تنظیمات و پلن",
    workspaces: "فضاهای کاری",
    agency: "آژانس",
    audits: "آنالیز پیج",
    admin: "مدیریت سامانه",
  },
  login: {
    title: "ورود به موتور رشد",
    phone: "شماره‌ی موبایل",
    sendCode: "دریافت کد",
    code: "کد پیامک‌شده",
    verify: "ورود",
    signupTitle: "حساب ندارید؟ ثبت‌نام کنید",
    firstName: "نام",
    lastName: "نام خانوادگی",
    signup: "ثبت‌نام و دریافت کد",
    devHint: "در محیط توسعه کد ۰۰۰۰ است.",
  },
  workspaces: {
    title: "فضاهای کاری",
    create: "فضای کاری تازه",
    name: "نام کسب‌وکار",
    vertical: "صنف",
    slug: "آدرس انگلیسی (اختیاری)",
    none: "هنوز فضای کاری ندارید. اولین کسب‌وکار را بسازید.",
  },
  dashboard: {
    title: "سنجش",
    period: "۳۰ روز گذشته",
    registrations: "ثبت‌نام آنلاین",
    revenue: "درآمد ردیابی‌شده",
    outside: "از خارج شهرستان",
    adminTime: "زمان ادمین در هفته (تخمین)",
    minutes: "دقیقه",
    baselineFrom: "پیش از شروع:",
    funnel: "قیف این ماه",
    bySource: "ثبت‌نام به تفکیک منبع",
    byChannel: "ثبت‌نام به تفکیک کانال",
    attention: "توجه (آخرین آمار هر پست)",
    bottleneck: "گلوگاه",
    bottleneckText: "از «{from}» به «{to}» فقط {rate} می‌رسند؛ این مرحله را بهتر کنید.",
    steps: { views: "بازدید", clicks: "کلیک لینک", form_starts: "شروع فرم", payments: "پرداخت" } as Record<string, string>,
    metrics: { views: "بازدید", reach: "دسترسی", likes: "لایک", comments: "کامنت", saves: "ذخیره", shares: "اشتراک" } as Record<string, string>,
    direct: "مستقیم",
    coupon: "کد",
  },
  queue: {
    title: "صف تأیید",
    pending: "در انتظار تأیید",
    scheduled: "زمان‌بندی‌شده",
    processing: "در حال ساخت",
    published: "منتشرشده",
    rejected: "ردشده",
    failed: "ساخت ناموفق",
    approve: "تأیید و انتشار",
    schedule: "زمان‌بندی",
    reject: "رد",
    rejectReason: "دلیل رد (اختیاری)",
    editCaption: "ویرایش با AI",
    instruction: "چه چیزی عوض شود؟ مثلاً «اسم آقای رضایی را هم بیاور»",
    fixSubtitle: "اصلاح زیرنویس",
    fixHint: "مثلاً: شطری -> شتری",
    subtitles: "— زیرنویس —",
    trackedLink: "لینک ردیابی",
    qc: "کنترل کیفیت",
    tagGuessed: "تگ حدس زده شد؛ تأیید یا تغییر دهید:",
    publishAt: "زمان انتشار",
    autoApprove: "انتشار خودکار در صورت بی‌پاسخی:",
    upload: "بارگذاری فیلم از پنل",
    uploadCaption: "تگ و توضیح (مثلاً #گزارش_برنامه برنامه‌ی جمعه)",
    uploading: "در حال ارسال…",
    queued: "در صف ساخت قرار گرفت",
    faces: "چهره‌ی واضح در تصویر: {n}",
    seconds: "{n} ثانیه",
    rate: "نمره‌ی این پیش‌نویس",
    statusPublished: "منتشر شد",
    statusFailed: "ناموفق",
    statusHandoff: "منتظر انتشار دستی",
    kinds: { reel: "ریلز", story: "استوری", full: "نسخه‌ی کامل", message: "پست" } as Record<string, string>,
  },
  qc: {
    "qc.length_ok": "طول متن‌ها درست است",
    "qc.length_bad": "متن برای این کانال‌ها طولانی است: {channels}",
    "qc.glossary_ok": "واژه‌نامه: اسم‌ها درست است",
    "qc.glossary_bad": "واژه‌نامه: بررسی کنید: {words}",
    "qc.banned_ok": "واژه‌ی ممنوعه ندارد",
    "qc.banned_bad": "واژه‌ی ممنوعه: {words}",
    "qc.cta_ok": "دعوت به اقدام دارد",
    "qc.cta_bad": "دعوت به اقدام ندارد: {channels}",
    "qc.link_ok": "لینک ردیابی دارد",
    "qc.link_bad": "لینک ردیابی ندارد: {channels}",
    "qc.faces_unknown": "بررسی چهره انجام نشد",
    "qc.faces_consent": "چهره‌ی {count} نفر واضح است؛ رضایت انتشار گرفته شده؟",
    "qc.music_missing": "کتابخانه‌ی موسیقی آزاد خالی است؛ بدون موسیقی ساخته شد",
  } as Record<string, string>,
  channels: {
    title: "کانال‌ها",
    names: { instagram: "اینستاگرام", bale: "بله", telegram: "تلگرام", aparat: "آپارات", eitaa: "ایتا", rubika: "روبیکا", site: "سایت" } as Record<string, string>,
    add: "افزودن کانال",
    type: "نوع کانال",
    name: "نام",
    secretSet: "ذخیره شده (برای تغییر، مقدار تازه بنویسید)",
    test: "آزمایش اتصال",
    healthy: "سالم",
    broken: "مشکل دارد",
    unchecked: "بررسی نشده",
    connectInstagram: "اتصال اینستاگرام (API رسمی)",
    instagramHandoff: "انتشار دستی یک‌کلیکی (بدون API)",
    instagramMode: "حالت انتشار اینستاگرام",
    disable: "غیرفعال کردن",
    fields: {
      bot_token: "توکن ربات",
      chat_id: "شناسه‌ی کانال عمومی (مثلاً @kanal یا -100…)",
      username: "نام کاربری کانال",
      raw_chat_id: "شناسه‌ی گروه یا کانال خصوصی محتوای خام",
      discussion_chat_id: "شناسه‌ی گروه بحث کانال (کامنت‌ها)",
      token: "توکن",
      category: "شماره‌ی دسته‌ی آپارات",
      password: "رمز آپارات",
    } as Record<string, string>,
    hints: {
      bale: "ربات را ادمین کانال کنید. بله به ربات پست کانال نمی‌دهد؛ ادمین‌ها فیلم را در گروه خصوصی با ربات یا مستقیم به ربات بفرستند.",
      telegram: "ربات را ادمین کانال عمومی، کانال محتوای خام و گروه بحث کنید.",
      eitaa: "توکن را از eitaayar.ir بگیرید.",
      rubika: "ربات روبیکا را ادمین کانال کنید.",
      aparat: "زیرنویس SRT بعد از انتشار در ربات برایتان فرستاده می‌شود تا در پنل آپارات اضافه کنید.",
      instagram: "با اتصال رسمی، انتشار و آمار و کامنت خودکار است. دایرکت‌ها از این راه خوانده نمی‌شوند؛ دعوت به اقدام‌ها مخاطب را به ربات بله یا تلگرام می‌برند.",
      site: "هر پست یک صفحه‌ی سئوشده در سایت خودتان دارد.",
    } as Record<string, string>,
    caps: "قابلیت‌ها: انتشار خودکار {auto} · آمار {metrics} · کامنت {comments} · حداکثر {mb} مگابایت",
  },
  team: {
    title: "اعضا",
    add: "افزودن عضو",
    name: "نام",
    role: "نقش",
    roles: { owner: "مالک", operator: "اپراتور", approver: "تأییدکننده", sender: "فرستنده‌ی محتوا" } as Record<string, string>,
    linkCode: "کد اتصال ربات",
    linkHint: "عضو این را برای ربات بفرستد: /start {code}",
    newCode: "کد تازه",
    bound: "وصل به ربات",
  },
  brand: {
    title: "کیت برند",
    version: "نسخه‌ی {n}",
    questionnaire: "پرسش‌نامه‌ی ۱۰ دقیقه‌ای",
    questions: {
      one_sentence: "کسب‌وکارت را در یک جمله برای یک غریبه توضیح بده.",
      ideal_customer: "مشتری ایده‌آلت کیست؟ (سن، شهر، چه می‌خواهد)",
      three_am_worry: "چه دغدغه‌ای «ساعت ۳ صبح» مشتری‌ات را بیدار نگه می‌دارد؟",
      three_words: "سه کلمه که می‌خواهی مردم درباره‌ات بگویند.",
      never_list: "چه چیزهایی را هرگز نمی‌خواهی در صفحه‌ات ببینی؟",
      liked_pages: "سه پیج که سبکشان را دوست داری.",
      assets_note: "لوگو، عکس‌های موجود و ۵ پستی که بیشتر دوستشان داری را توضیح بده.",
    } as Record<string, string>,
    regenerate: "ساخت با AI",
    generating: "در حال ساخت کیت برند…",
    colors: "رنگ‌ها",
    primary: "رنگ اصلی",
    accent: "رنگ کمکی",
    text: "رنگ متن زیرنویس",
    fonts: "فونت",
    heading: "تیتر",
    body: "متن",
    tone: "لحن",
    adjectives: "سه صفت (هست)",
    anti: "سه ضدصفت (نیست)",
    doExamples: "✓ این‌طور بنویس",
    dontExamples: "✗ این‌طور ننویس",
    pillars: "ستون‌های محتوا",
    goals: { attract: "جذب", trust: "اعتماد", convert: "تبدیل" } as Record<string, string>,
    glossary: "واژه‌نامه‌ی زیرنویس (هر خط یک اسم)",
    banned: "فهرست ممنوعه (هر خط یکی)",
    bio: "پیشنهاد بیو",
    highlights: "هایلایت‌ها",
    logo: "لوگو (PNG)",
    versions: "نسخه‌ها",
    oneLine: "هر خط یکی",
    preview: "پیش‌نمایش زیرنویس",
    previewText: "از قله‌ی شتری، کویر تا افق پیداست",
  },
  tags: {
    title: "تگ‌ها (دستور پخت)",
    hint: "ادمین فقط یک کلمه می‌نویسد؛ هر تگ همه‌چیز را می‌داند.",
    tag: "تگ",
    goal: "هدف",
    pillar: "ستون محتوا",
    style: "سبک کپشن",
    cta: "دعوت به اقدام",
    length: "طول ویدیو (ثانیه)",
    min: "حداقل",
    max: "حداکثر",
    aspects: "قاب‌ها",
    subtitle: "زیرنویس",
    subtitleModes: { word: "کلمه‌به‌کلمه", sentence: "جمله‌ای", none: "بدون زیرنویس" } as Record<string, string>,
    overlay: "متن روی تصویر",
    overlays: { date_price: "تاریخ و قیمت", title: "تیتر", name_role: "اسم و سمت", none: "هیچ" } as Record<string, string>,
    music: "موسیقی آزاد",
    channels: "کانال‌ها",
    timing: "زمان انتشار",
    timings: { immediate: "فوری", next_day_evening: "عصر روز بعد", best_hour: "ساعت پربازدید" } as Record<string, string>,
    hour: "ساعت",
    reminder: "یادآور (روز بعد از انتشار)",
    lowRisk: "کم‌ریسک (انتشار خودکار پس از ۲۴ ساعت، با رضایت مالک)",
    new: "تگ تازه",
  },
  calendar: {
    title: "تقویم محتوا",
    generate: "تولید خودکار ماه",
    generating: "در حال چیدن ماه…",
    weekdays: ["شنبه", "یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنج‌شنبه", "جمعه"],
    waiting: "منتظر فیلم",
    requested: "سفارش داده شد",
    legend: "رنگ هر خانه = هدف محتوا · خاکستری = منتظر محتوای خام · کشیدن و رها کردن برای جابه‌جایی",
    prev: "ماه قبل",
    next: "ماه بعد",
    kinds: { post: "پست", reel: "ریلز", story: "استوری" } as Record<string, string>,
    addSlot: "افزودن خانه",
  },
  feedback: {
    title: "صندوق بازخورد",
    categories: { purchase_question: "سؤال خرید", praise: "تعریف", criticism: "انتقاد", spam: "اسپم", idea: "ایده‌ی محتوا", other: "سایر", unsorted: "دسته‌نشده" } as Record<string, string>,
    all: "همه",
    suggestion: "پیشنهاد",
    copySend: "کپی و ارسال",
    sendBot: "ارسال از ربات",
    handled: "رسیدگی شد",
    toIdea: "به بانک ایده",
    alerted: "به مدیر اطلاع داده شد",
  },
  competitors: {
    title: "تحلیل رقبا",
    hint: "فقط پیج‌های عمومی، فقط عدد؛ اطلاعات شخصی کامنت‌گذارها ذخیره نمی‌شود. هدف یاد گرفتن الگوست، نه کپی.",
    add: "افزودن پیج",
    handle: "آیدی پیج",
    kind: "نوع",
    kinds: { direct: "رقیب مستقیم", substitute: "رقیب جایگزین", pattern: "الگوی محتوایی" } as Record<string, string>,
    followers: "دنبال‌کننده",
    perWeek: "پست/هفته",
    engagement: "تعامل",
    bestHook: "قالب برنده",
    addPosts: "افزودن پست‌های برتر",
    url: "لینک",
    views: "بازدید",
    likes: "لایک",
    comments: "کامنت",
    caption: "خط اول کپشن",
    price: "قیمت پیشنهاد",
    screenshots: "یا اسکرین‌شات بفرستید",
    analyze: "تحلیل با AI",
    analyzing: "تحلیل در صف است؛ چند دقیقه بعد به‌روزرسانی کنید.",
    patterns: "الگوهای برنده",
    gaps: "شکاف‌ها",
    suggestions: "پیشنهاد برای شما",
    orderVideo: "سفارش فیلم به ادمین",
    ordered: "سفارش در ربات فرستاده شد",
    ratio: "× نسبت به میانگین همان پیج",
    hooks: { question: "سؤال", number: "عدد", contrast: "تضاد", before_after: "قبل و بعد", silent_scenery: "منظره‌ی بی‌کلام", mistakes_list: "لیست اشتباه‌ها", story: "داستان", other: "سایر" } as Record<string, string>,
  },
  sales: {
    title: "فروش و لینک‌ها",
    offers: "پیشنهادها (برنامه‌ها)",
    offerTitle: "عنوان",
    slug: "آدرس انگلیسی",
    price: "قیمت (تومان)",
    capacity: "ظرفیت",
    startsAt: "تاریخ و ساعت",
    description: "توضیح",
    seatsLeft: "جای خالی",
    registrations: "ثبت‌نام‌ها",
    coupons: "کدهای تخفیف و اینفلوئنسر",
    code: "کد",
    influencer: "اینفلوئنسر",
    discount: "درصد تخفیف",
    links: "لینک‌های ردیابی",
    target: "مقصد",
    label: "برچسب",
    clicks: "کلیک",
    keywords: "کلمه‌های ربات",
    keywordHint: "«کلمه‌ی کویر را به ربات بفرستید»: جواب ربات و لید ثبت‌شده",
    keyword: "کلمه",
    reply: "جواب ربات",
    leads: "لیدهای ربات",
    ideas: "بانک ایده",
    status: { paid: "پرداخت‌شده", pending_payment: "در انتظار پرداخت", failed: "ناموفق" } as Record<string, string>,
    source: "منبع",
    city: "شهر",
    open: "صفحه‌ی ثبت‌نام",
  },
  reports: {
    title: "گزارش‌های هفتگی",
    runNow: "ساخت گزارش هفته‌ی گذشته",
    queued: "در صف ساخت است",
    sent: "در ربات فرستاده شد",
    notSent: "فرستاده نشد (کسی به ربات وصل نیست)",
  },
  settings: {
    title: "تنظیمات و پلن",
    plan: "پلن",
    usage: "مصرف این ماه",
    videos: "ویدیو",
    aiCalls: "درخواست AI",
    buy: "خرید",
    plans: { free: "رایگان", basic: "پایه", pro: "حرفه‌ای", agency: "آژانس" } as Record<string, string>,
    perMonth: "در ماه",
    consent: "رضایت به انتشار خودکار تگ‌های کم‌ریسک پس از ۲۴ ساعت بی‌پاسخی",
    homeCity: "شهر خودتان (برای سنجش «از خارج شهرستان»)",
    bestHour: "ساعت پربازدید (خودکار از آمار یاد گرفته می‌شود)",
    weeklySlots: "قالب هفتگی",
    posts: "پست",
    reels: "ریلز",
    stories: "استوری",
    baseline: "عددهای پیش از شروع (برای مقایسه)",
    baseRegs: "ثبت‌نام آنلاین در ماه",
    baseHours: "ساعت کار ادمین در هفته",
    paid: "پرداخت انجام شد؛ پلن فعال است.",
    payFailed: "پرداخت انجام نشد.",
  },
  audit: {
    title: "آنالیز رایگان پیج اینستاگرام",
    lead: "در ۲ دقیقه ببینید مشکل پیجتان چیست: نمره‌ی رشد، ۵ کار اول و ۳ پست بازنویسی‌شده.",
    handle: "آیدی پیج",
    vertical: "صنف",
    phone: "شماره‌ی موبایل",
    screenshots: "سه اسکرین‌شات: پروفایل، شبکه‌ی پست‌ها، Insights",
    submit: "شروع آنالیز",
    waiting: "در حال آنالیز… این صفحه خودش به‌روز می‌شود.",
    failed: "آنالیز انجام نشد. دوباره تلاش کنید.",
    score: "نمره‌ی رشد",
    average: "میانگین صنف: {n}",
    axes: { bio: "بیو و پروفایل", cadence: "نظم انتشار", hooks: "قالب‌ها", engagement: "تعامل", brand: "یک‌دستی برند", conversion: "مسیر تبدیل" } as Record<string, string>,
    fixes: "۵ کار اول (بیشترین اثر)",
    rewrites: "نمونه‌ی بازنویسی",
    before: "قبل:",
    after: "بعد:",
    wantService: "می‌خواهم این کارها برایم انجام شود",
    followers: "دنبال‌کننده",
    posts: "پست",
    ownAudit: "آنالیز پیج خودم (API رسمی)",
    leads: "لیدهای آنالیز",
    wants: "درخواست خدمات",
  },
  agency: {
    title: "پنل آژانس",
    create: "ساخت آژانس",
    name: "نام آژانس",
    clients: "مشتری‌ها",
    pending: "منتظر تأیید",
    regsMonth: "ثبت‌نام این ماه",
    openQuestions: "سؤال خرید بی‌جواب",
    whiteLabel: "برند سفید (White-label)",
    displayName: "نام محصول برای مشتری‌ها",
    color: "رنگ اصلی",
    domain: "دامنه‌ی لینک‌ها (مثلاً go.example.ir)",
    newClient: "مشتری تازه",
  },
  admin: {
    title: "صف کارهای سامانه",
    retry: "اجرای دوباره",
    statuses: { failed: "ناموفق", queued: "در صف", running: "در حال اجرا", done: "انجام‌شده" } as Record<string, string>,
  },
  errors: {
    generic: "مشکلی پیش آمد. دوباره تلاش کنید.",
    auth_required: "دوباره وارد شوید.",
    token_invalid: "نشست منقضی شده؛ دوباره وارد شوید.",
    account_not_found: "حسابی با این شماره نیست؛ ثبت‌نام کنید.",
    otp_invalid: "کد درست نیست.",
    otp_expired: "کد منقضی شده؛ کد تازه بگیرید.",
    otp_locked: "چند بار اشتباه زدید؛ کد تازه بگیرید.",
    otp_too_soon: "یک دقیقه صبر کنید و دوباره بخواهید.",
    phone_invalid: "شماره را به شکل ۰۹xxxxxxxxx بنویسید.",
    workspace_forbidden: "به این فضای کاری دسترسی ندارید.",
    role_required: "نقش شما اجازه‌ی این کار را ندارد.",
    plan_limit_reached: "سقف ماهانه‌ی پلن پر شده است.",
    post_not_editable: "این پست دیگر قابل تغییر نیست.",
    post_not_pending: "این پست قبلاً تصمیم‌گیری شده است.",
    subtitle_fix_unclear: "این‌طور بنویسید: اشتباه -> درست",
    bot_token_invalid: "توکن ربات کار نمی‌کند.",
    instagram_not_configured: "اتصال اینستاگرام روی سرور تنظیم نشده است.",
    instagram_not_connected: "اول اینستاگرام را وصل کنید.",
    no_bot_recipient: "هنوز کسی از اعضا به ربات وصل نیست.",
    no_competitor_posts: "اول چند پست رقیب اضافه کنید.",
    audit_limit: "امروز به اندازه‌ی کافی آنالیز گرفته‌اید.",
    slug_taken: "این آدرس گرفته شده است.",
    tag_exists: "این تگ وجود دارد.",
    validation_error: "یکی از خانه‌ها درست پر نشده است.",
    file_too_large: "فایل خیلی بزرگ است.",
    reply_not_supported: "این کانال جواب از پنل را پشتیبانی نمی‌کند؛ کپی کنید و در خود برنامه بفرستید.",
    payment_unavailable: "درگاه پرداخت جواب نمی‌دهد.",
    logo_png_required: "لوگو باید PNG باشد.",
  } as Record<string, string>,
};

const faDigits = (value: string): string => value.replace(/[0-9]/g, (d) => String.fromCharCode(0x06f0 + Number(d)));

/** Fill {placeholders}; digits in the values become Persian digits. */
export function fill(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (_, k: string) => faDigits(String(values[k] ?? "")));
}

export function errorText(code: string): string {
  return fa.errors[code] ?? fa.errors.generic ?? "";
}
